### ISSUE TITLE
Saleor CLI + Saleor Platform integration

### ISSUE THREAD

**Issue by lkostrowski** [saleor/cli#277]
# Context

CLI should allow to create entire Saleor stack for local development with a single command. Now, Saleor Platform must be discovered, while CLI is possibly the main developer's tool.

# Solution

Introduce `saleor bootstrap` (or something like this) command. It will clone [saleor-platform](https://github.com/saleor/saleor-platform) repo to selected directory and run `make` script to build it. Later, it will show instructions how to use it.

This command can be included in homepage of Saleor and Docs

# Local CLI usage

At the moment, CLI only works for cloud and can be working with staging if env is set.

If local Docker container is running, CLI should use it as a target.

Introduce a way to alter this behavior. For example `saleor.json` file can be checked locally (created by CLI during `bootstrap`) and it can contain a localhost for container instead cloud URL. If `saleor.json` is not found, it can search in default location

# Versioning

By default, CLI should bootstrap last stable platform project (with current submodules). However, platform should be versioned (tags), e.g `v3.6`, so users can go back. 

This feature can be added in second iteration

**Comment by lkostrowski** [comment]
@timuric what do you think?

**Comment by lkostrowski** [comment]
@peelar I'd like to know you opinion too

**Comment by peelar** [comment]
I 💯 agree with the idea of CLI being the headquarters of a Saleor developer. I like the sound of `saleor bootstrap` and trying to detect what is the environmental context of executing a command (whether it's cloud or local development). Let's push this vision further:

Imagine you cloned the `saleor/saleor` repository, and booted it up with Docker.

You run `saleor` in the CLI to see all the available commands. You choose to set up a storefront, and the CLI displays:

> We detected a Saleor Docker container running.
> Do you want to set up Storefront for local development? (y/n)
>  ~ y

The repository is then cloned, and we do whatever we can to make it work with the local Saleor API out of the box (set up the environment variables, prepare it for deployment, etc.). 

But let's say the user said "no" to the question above:
> We detected a Saleor Docker container running.
> Do you want to set up Storefront for local development? (y/n)
>  ~ n

The question was asked only because we detected the Docker container (or `saleor.json`, I dunno). It was based on the context of the environment it was executed in.

If the user doesn't want to use the local setup, we can proceed with the Cloud flow:
> Select cloud environment:
> ○ korniszonki
> ○ qwerty
> ...

---

What I am saying is: what if we bake in the logic of detecting the environment to every possible command? What if we make our top-level commands in the CLI agnostic of the environment, so there is no `saleor xyz local` and `saleor xyz cloud`?

**Comment by lkostrowski** [comment]
Idea on naming - `saleor platform CMD` like `saleor platform create`

Idea on creation - extra flags:
`saleor platform create --only-api`

Another idea - interactive builder
